version: '3.7'

services:
  templating:
    image: ${OWNER}/templating
    build:
      context: ./microservicios/templating
      dockerfile: Dockerfile
    env_file: .env
    environment:
      TEMPLATES_DIR: /tmp/templates
      RENDERED_DIR: /tmp/rendered
    volumes:
      - ./templates:/tmp/templates
      - ./config_files:/tmp/rendered:rw

  db:
    image: mariadb
    container_name: ${PROJECT_NAME}_db_development
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config_files/db:/docker-entrypoint-initdb.d
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--silent"]
    env_file: .env
    networks:
        - fs_network
    ports:
      - "${EXTERNAL_DB_PORT}:${DB_PORT}"
    expose:
      - 3306

  api:
    image: ${OWNER}/${PROJECT_NAME}-api-development
    build: 
      context: ./microservicios/api
      dockerfile: Dockerfile.development
    container_name: ${PROJECT_NAME}_api_development
    restart: always
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
    env_file: .env
    volumes:
      - ./microservicios/api:/api
      - /api/node_modules
    networks:
      - fs_network
    ports:
      - "${API_PORT}:${API_PORT}"

  dashboard:
    image: ${OWNER}/${PROJECT_NAME}-dashboard-development
    build:
      context: ./microservicios/dashboard
      dockerfile: Dockerfile.development
    restart: always
    env_file: .env
    container_name: ${PROJECT_NAME}_dashboard_development
    restart: unless-stopped
    ports:
      - "${DASHBOARD_EXTERNAL_PORT}:80"
    stdin_open: true
    tty: true
    volumes:
      - ./microservicios/dashboard:/dashboard
      - /dashboard/node_modules
    networks:
      - fs_network

  keycloak:
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    build: 
      context: ./microservicios/keycloak/server
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-keycloak
    restart: unless-stopped
    volumes:
      - ./config_files/keycloak/realm-export.json:${KEYCLOAK_IMPORT}
      - ./microservicios/keycloak/themes/default_theme:/opt/jboss/keycloak/themes/default_theme
    environment:
      KEYCLOAK_IMPORT: ${KEYCLOAK_IMPORT}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: ${KEYCLOAK_DB_VENDOR}
      DB_ADDR: ${KEYCLOAK_DB_HOST}
      DB_DATABASE: ${KEKCLOAK_DB_NAME}
      DB_USER: ${KEKCLOAK_DB_USER}
      DB_PASSWORD: ${KEKCLOAK_DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: public
      PROXY_ADDRESS_FORWARDING: 'true'
      KEYCLOAK_WELCOME_THEME: default_theme
      KEYCLOAK_DEFAULT_THEME: default_theme
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
    depends_on:
      - db
    ports:
      - '8080:8080'
      - '8443:8443'
    networks:
      - fs_network

  proxy:
    image: nginx:1.15.1
    container_name: proxy
    restart: unless-stopped
    volumes:
      - ./config_files/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config_files/proxy/proxy.conf:/etc/nginx/proxy.conf:ro
      # - ./favicon.ico:/etc/nginx/favicon.ico
    ports:
      - "80:80"
      - '443:443'
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - fs_network


networks:
  fs_network:
    driver: bridge

volumes:
  mysql_data: