CREATE USER '{{ KEKCLOAK_DB_USER }}'@'%' IDENTIFIED BY  '{{ KEKCLOAK_DB_PASSWORD }}';
CREATE USER '{{ API_DB_USER }}'@'%' IDENTIFIED BY  '{{ API_DB_PASSWORD }}';

CREATE DATABASE {{ KEKCLOAK_DB_NAME }};
CREATE DATABASE {{ API_DB_NAME }};

GRANT ALL PRIVILEGES ON {{ KEKCLOAK_DB_NAME }}.* TO '{{ KEKCLOAK_DB_USER }}'@'%';
GRANT ALL PRIVILEGES ON {{ API_DB_NAME }}.* TO '{{ API_DB_USER }}'@'%';

FLUSH PRIVILEGES;