FROM node:13-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/package.json

RUN yarn


ARG REACT_APP_GQL_HTTP_URL
ENV REACT_APP_GQL_HTTP_URL=$REACT_APP_GQL_HTTP_URL
ARG REACT_APP_GQL_WS_URL
ENV REACT_APP_GQL_WS_URL=$REACT_APP_GQL_WS_URL

COPY . .

ENV PORT=80
CMD ["yarn", "start"]